# docs: https://docs.couchdb.org/en/latest/install/docker.html
# source: https://github.com/apache/couchdb-docker
# image: https://hub.docker.com/_/couchdb

version: '3.8'

services:
  couchdb:
    image: couchdb:latest
    container_name: relax
    restart: always
    ports:
      - 5984:5984
    volumes:
      - couchdb_data:/opt/couchdb/data
      - couchdb_config:/opt/couchdb/etc/local.d
      - couchdb_log:/opt/couchdb/var/log
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password

volumes:
  couchdb_data:
  couchdb_config:
  couchdb_log:
